version: 2.0

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: docker:dind
        environment:
          DOCKER_IMG: "ompcloud-test"
          DOCKER_REPO: "ompcloud/ompcloud-test"
    steps:
      - setup_docker_engine
      - checkout
      - run: docker build --rm=false -f Dockerfile -t $DOCKER_REPO:$CIRCLE_SHA1 .
